version: '3'

services:
  db:
    image: postgres
    environment:
    - POSTGRES_USER=shushan
    - POSTGRES_PASSWORD=shushan
    - POSTGRES_DB=regio_helden
  web:
    build: .
    command: bash -c "sleep 1 && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db